# Generated by Django 5.2.7 on 2025-10-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['start_page']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='upload',
            name='ocr_pages',
            field=models.IntegerField(default=0, help_text='Number of pages processed with OCR'),
        ),
        migrations.AddField(
            model_name='upload',
            name='ocr_used',
            field=models.BooleanField(default=False, help_text='Whether OCR was used for this upload'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='chunk_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.upload'),
        ),
    ]
