# Generated by Django 5.2.7 on 2025-10-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chunk_options_alter_plan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_goal', models.TextField(blank=True, help_text="User's stated goal", null=True)),
                ('sort_method', models.CharField(default='hybrid', help_text='Sorting method: hybrid/urgency/foundational/pages/content/complexity', max_length=50)),
                ('constraints', models.TextField(blank=True, help_text='User preferences and constraints', null=True)),
                ('time_input', models.JSONField(default=dict, help_text='Time availability: {years, months, weeks, days, hours}')),
                ('total_hours', models.FloatField(default=0, help_text='Total hours calculated from time_input')),
                ('total_files', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('plan_json', models.JSONField(default=dict, help_text='Complete generated plan with tasks and schedule')),
                ('execution_time', models.FloatField(default=0, help_text='Time taken to generate plan (seconds)')),
                ('tool_calls', models.IntegerField(default=0, help_text='Number of AI tool calls made')),
                ('ocr_pages_total', models.IntegerField(default=0, help_text='Total OCR pages across all uploads')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Study Plan History',
                'verbose_name_plural': 'Study Plan Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['upload', 'start_page'], name='core_chunk_upload__cc3dad_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['user', 'status'], name='core_upload_user_id_a8fd32_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['created_at'], name='core_upload_created_9766ea_idx'),
        ),
        migrations.AddField(
            model_name='studyplanhistory',
            name='uploads',
            field=models.ManyToManyField(help_text='PDFs used in this plan', related_name='study_plans', to='core.upload'),
        ),
        migrations.AddField(
            model_name='studyplanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studyplanhistory',
            index=models.Index(fields=['user', '-created_at'], name='core_studyp_user_id_09520a_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanhistory',
            index=models.Index(fields=['status'], name='core_studyp_status_5f3614_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanhistory',
            index=models.Index(fields=['sort_method'], name='core_studyp_sort_me_b07551_idx'),
        ),
    ]
