# Generated by Django 5.2.7 on 2025-10-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studyplanhistory_chunk_core_chunk_upload__cc3dad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
