# Generated by Django 4.2.25 on 2025-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prioritizationfeedback_quizanswer_quizquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='focus_task_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
