# Generated by Django 4.2.25 on 2025-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quizsession_focus_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanhistory',
            name='kanban_state',
            field=models.JSONField(blank=True, default=dict, help_text='Saved state of kanban columns'),
        ),
        migrations.AddField(
            model_name='studyplanhistory',
            name='project_name',
            field=models.CharField(blank=True, help_text='User-defined project name', max_length=255, null=True),
        ),
    ]
