# Generated by Django 4.2.25 on 2025-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studyplanhistory_kanban_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.TextField(blank=True, help_text='Option C', null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.TextField(blank=True, help_text='Option D', null=True),
        ),
    ]
